/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f411.h>
#include "gpio.h"
#include <spi.h>

int main(void)
{
	GPIO_OUTPUT_Init(GPIOC, GPIO_PIN_13, OUTPUT_PP, HIGH_SPEED);
	GPIO_INPUT_Init(GPIOA, GPIO_PIN_0, PULL_UP);


    /* Loop forever */
	while(1){
		if(GPIO_Read_Pin(GPIOA, GPIO_PIN_0)==1){
			GPIO_Write_Pin(GPIOC, GPIO_PIN_13, HIGH);
		}
	else
		GPIO_Write_Pin(GPIOC, GPIO_PIN_13, LOW);
	}
}
